#!/bin/bash   

#id no existe:
#[ "`grep x:$id /etc/passwd`" == "" ]


#usuario no coincide:
#linea_id="`grep x:$id /etc/passwd`"
#linea_id_con_espacios=$(echo $linea_id|sed 's/:/ /g')
#nombre_en_linea_id=`echo $linea_id_con_espacios | awk '{print $1}'`
#["$nombre_en_linea_id" != "$nombre" ]


#no existe ese usuario:
#linea_usuario="`grep $nombre:x: /etc/passwd`"
#[ "$linea_usuario" == "" ]


#~ cambiar usuario:
#~ linea_id="`grep x:$id /etc/passwd`"
#~ linea_id_con_espacios=$(echo$linea_id|sed 's/:/ /g')
#~ usuario_viejo=`echo $linea_id_con_espacios | awk '{print $1}'`
#~ path_viejo=`echo $linea_id_con_espacios | awk '{print $6}'`
#~ usermod -l $nombre $usuario_viejo
#~ mv $path_viejo /home/$nombre
#~ usermod -d /home/$nombre  $nombre


#~ cambiar grupo del usuario:
#~ linea_grupo="`grep $nombre:x /etc/group`"
#~ linea_grupo_con_espacios=$(echo $linea_grupo|sed 's/:/ /g')
#~ id_grupo=`echo $linea_grupo_con_espacios | awk '{print $3}'`
#~ linea_id="`grep x:$id /etc/passwd`"
#~ linea_id_con_espacios=$(echo$linea_id|sed 's/:/ /g')
#~ nombre_usuario=`echo $linea_id_con_espacios | awk '{print $1}'`
#~ usermod -g $id_grupo $nombre_usuario

#crear usuario con id correspondiente:
#adduser --uid $id $nombre

#~ grupo no coincide:
#~ linea_id="`grep x:$id /etc/passwd`"
#~ linea_id_con_espacios=$(echo$linea_id|sed 's/:/ /g')
#~ id_grupo_en_linea_id=`echo $linea_id_con_espacios | awk '{print $4}'`
#~ linea_id_grupo="`grep x:$id_grupo_en_linea_id /etc/group`"
#~ nombre_grupo=`echo $linea_id_con_espacios | awk '{print $1}'`
#~ [ $nombre_grupo != nombre]

#~ grupo existe:
#~ linea_grupo="`grep $nombre:x /etc/group`"
#~ [ $linea_grupo != "" ]

#~ crear grupo:
#~ addgroup $nombre 
if [ $# -lt 1 ]
then
echo Se debe suministrar el nombre de archivo de una lista con el siguiente formato:
echo id tipo usuario [grupo] clave
echo
echo Recuerde ejecutar como superusuario!! 
exit
fi
while read line ; do 
  id=`echo $line | awk '{print $1}'` 		
  tipo=`echo $line | awk '{print $2}'`
  nombre=`echo $line | awk '{print $3}'`
  grupo_input=`echo $line | awk '{print $4}'`
  numero_param=`echo $line | awk '{print NF}'`
  password=
  if [ $numero_param -le 4 ] # si hay un grupo entre los parametros
    then
    password=`echo $line | awk '{print $4}'`
    else
    password=`echo $line | awk '{print $5}'`
  fi
  
  if (id no existe) {
    if (tipo es U) {
      if (no existe ese usuario) {
        if (si hay un grupo entre los parametros ) {
          crear usuario con id correspondiente
        }
        else {
          crear usuario con id Y GRUPO correspondientes
        }
      }
      else {
        echo "Ese id no existe pero el nombre de usuario ya esta ocupado."
      }
      if (tipo es G ) {
        echo Error: no existe el id $id y no se suministro un nombre de 
  usuario
      }
    }
  }
    
  else #------> o sea que id si existe.
  {
    if (tipo es U ) {
      if (usuario no coincide) {
        if (no existe ese usuario) {
          cambiar usuario
        }
        else  {
          echo "Error: no se puede cambiar el nombre de usuario porque ya existe otro usuario con ese nombre"
        }
      }
      
      if (grupo no existe ) {
        creo el grupo
      }
      cambiar grupo del usuario:
      // Comentario : Si no hace falta cambiar el grupo no pasa nada igual
    }
    if (tipo es G y grupo no coincide ) {
      if(grupo no existe) {
        crear grupo
      }
      cambiar grupo del usuario:
    }
    
  }
  cambiar password
  cambiar ownership y grupo de los archivos del home



