package ubadbtools.deadlockAnalyzer.gui.forms;

import java.awt.Frame;

import javax.swing.GroupLayout;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

import ubadbtools.deadlockAnalyzer.common.Schedule;


/**
* This code was edited or generated using CloudGarden's Jigloo
* SWT/Swing GUI Builder, which is free for non-commercial
* use. If Jigloo is being used commercially (ie, by a corporation,
* company or business for any purpose whatever) then you
* should purchase a license for each developer using Jigloo.
* Please visit www.cloudgarden.com for details.
* Use of Jigloo implies acceptance of these licensing terms.
* A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR
* THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED
* LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE.
*/
@SuppressWarnings("serial")
public class AnalyzeScheduleDialog extends JDialog
{
	//[start] Constructor
    public AnalyzeScheduleDialog(Frame parent, boolean modal, Schedule log)
    {
    	super(parent, modal);
        initComponents();
        
        // Analizo cada aspecto del log
        //TODO: Completar
    }
    //[end]
    
    //[start] showDialog
    public static void showDialog(Frame parent, Schedule log)
    {
    	AnalyzeScheduleDialog dialog = new AnalyzeScheduleDialog(parent, true, log);
        dialog.setVisible(true);
    }
    //[end]
    
    //[start] ShowErrorMessage
	/**
     * Muestra un mensaje de error al usuario
     * @param message
     */
	public void ShowErrorMessage(String message)
	{
		JOptionPane.showConfirmDialog(
			this,
			message,
			"Error",
			JOptionPane.DEFAULT_OPTION,
			JOptionPane.ERROR_MESSAGE);
	}
	//[end]
	
    //[start] InitComponents (AUTO-GENERATED)
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	GroupLayout layout = new GroupLayout((JComponent)getContentPane());
    	getContentPane().setLayout(layout);
        butCerrar = new javax.swing.JButton();

        this.setTitle("Análisis de la historia");

        butCerrar.setText("Cerrar");
        {
        	jTextArea1 = new JTextArea();
        	jTextArea1.setText("Acá deben incluir el análisis de 2PL, S2PL y la detección de deadlocks (si fue seleccionada  previamente)");
        	jTextArea1.setLineWrap(true);
        }
        layout.setVerticalGroup(layout.createSequentialGroup()
        	.addContainerGap(36, 36)
        	.addComponent(jTextArea1, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
        	.addGap(341)
        	.addComponent(butCerrar, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        	.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setHorizontalGroup(layout.createSequentialGroup()
        	.addContainerGap(63, 63)
        	.addComponent(jTextArea1, 0, 242, Short.MAX_VALUE)
        	.addGap(23)
        	.addComponent(butCerrar, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        	.addContainerGap());
        butCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butCerrarMouseClicked(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents
	//[end]
    
    //[start] Eventos
    private void butCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCerrarMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_butCerrarMouseClicked
	//[end]
	
	//[start] Variables Form (AUTO-GENERATED)
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCerrar;
    private JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    //[end]
}
