/*
 * SelectScheduleTypeDialog.java
 *
 * Created on 6 de abril de 2009, 15:44
 */

package ubadbtools.recoveryLogAnalyzer.gui.forms;

import java.awt.Frame;
import java.util.Set;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import ubadbtools.recoveryLogAnalyzer.logRecords.EndCheckpointLogRecord;

import ubadbtools.recoveryLogAnalyzer.logRecords.RecoveryLogRecord;


/**
* This code was edited or generated using CloudGarden's Jigloo
* SWT/Swing GUI Builder, which is free for non-commercial
* use. If Jigloo is being used commercially (ie, by a corporation,
* company or business for any purpose whatever) then you
* should purchase a license for each developer using Jigloo.
* Please visit www.cloudgarden.com for details.
* Use of Jigloo implies acceptance of these licensing terms.
* A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR
* THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED
* LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE.
*/
@SuppressWarnings("serial")
public class EditLogRecordDialog extends javax.swing.JDialog {
    
	//[start] Atributos
	private RecoveryLogRecord logRecord = null;
	private Set<String> transactions;
	private Set<String> items;
	private Frame parent;
	//[end]
	
	//[start] Constructor
    public EditLogRecordDialog(java.awt.Frame parent, boolean modal, Set<String> transactions, Set<String> items)
    {
        super(parent, modal);
        initComponents();
        
        this.transactions = transactions;
        this.items = items;
        this.parent = parent;
    }
    //[end]
    
    //[start] showDialog
    public static RecoveryLogRecord showDialog(Frame parent, Set<String> transactions, Set<String> items)
    {
    	EditLogRecordDialog dialog = new EditLogRecordDialog(parent, true, transactions, items);
        dialog.setVisible(true);
        
        return dialog.logRecord;
    }
    //[end]
    
    //[start] InitComponents (AUTO-GENERATED)
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbgActionType = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbStart = new javax.swing.JRadioButton();
        rbUpdate = new javax.swing.JRadioButton();
        rbCommit = new javax.swing.JRadioButton();
        rbStartCheckpoint = new javax.swing.JRadioButton();
        rbEndCheckpoint = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        butCancelar = new javax.swing.JButton();
        butAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        rbgActionType.add(rbStart);
        rbStart.setSelected(true);
        rbStart.setText("Start"); // NOI18N
        rbStart.setName("rbStart"); // NOI18N
        jPanel1.add(rbStart);

        rbgActionType.add(rbUpdate);
        rbUpdate.setText("Update"); // NOI18N
        rbUpdate.setName("rbUpdate"); // NOI18N
        jPanel1.add(rbUpdate);

        rbgActionType.add(rbCommit);
        rbCommit.setText("Commit"); // NOI18N
        rbCommit.setName("rbCommit"); // NOI18N
        jPanel1.add(rbCommit);

        rbgActionType.add(rbStartCheckpoint);
        rbStartCheckpoint.setText("Start Checkpoint"); // NOI18N
        rbStartCheckpoint.setName("rbStartCheckpoint"); // NOI18N
        jPanel1.add(rbStartCheckpoint);

        rbgActionType.add(rbEndCheckpoint);
        rbEndCheckpoint.setText("End Checkpoint"); // NOI18N
        rbEndCheckpoint.setName("rbEndCheckpoint"); // NOI18N
        jPanel1.add(rbEndCheckpoint);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Tipo de registro"); // NOI18N

        butCancelar.setText("Cancelar"); // NOI18N
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });

        butAceptar.setText("Aceptar"); // NOI18N
        butAceptar.setName("jButton1"); // NOI18N
        butAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setVerticalGroup(layout.createSequentialGroup()
        	.addContainerGap()
        	.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        	.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
        	.addComponent(jPanel1, 0, 122, Short.MAX_VALUE)
        	.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
        	.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
        	    .addComponent(butAceptar, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        	    .addComponent(butCancelar, GroupLayout.Alignment.BASELINE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE))
        	.addContainerGap(18, 18));
        layout.setHorizontalGroup(layout.createSequentialGroup()
        	.addContainerGap(62, 62)
        	.addGroup(layout.createParallelGroup()
        	    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
        	        .addGap(0, 0, Short.MAX_VALUE)
        	        .addComponent(butAceptar, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        	        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
        	        .addComponent(butCancelar, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        	        .addGap(25))
        	    .addGroup(layout.createSequentialGroup()
        	        .addGap(0, 0, Short.MAX_VALUE)
        	        .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 151, GroupLayout.PREFERRED_SIZE))
        	    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
        	        .addGap(19)
        	        .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        	        .addGap(0, 49, Short.MAX_VALUE)))
        	.addContainerGap(43, 43));

        pack();
    }// </editor-fold>//GEN-END:initComponents
	//[end]
    
    //[start] Eventos
    private void butAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAceptarActionPerformed

    	// Genero el registro de log segun los valores en los controles del dialogo
    	if(rbStart.isSelected())
    		logRecord = StartLogRecordDialog.showDialog(parent, transactions);
    	else if(rbCommit.isSelected())
    		logRecord = CommitLogRecordDialog.showDialog(parent, transactions);
    	else if(rbUpdate.isSelected())
    		logRecord = UpdateLogRecordDialog.showDialog(parent, transactions,items);
        else if (rbStartCheckpoint.isSelected())
            logRecord = StartCheckpointDialog.showDialog(parent, transactions);
        else if (rbEndCheckpoint.isSelected())
            logRecord = new EndCheckpointLogRecord();

		this.setVisible(false);
    }//GEN-LAST:event_butAceptarActionPerformed

    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_butCancelarActionPerformed
    //[end]

    //[start] Variables Form (AUTO-GENERATED)
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAceptar;
    private javax.swing.JButton butCancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbCommit;
    private javax.swing.JRadioButton rbEndCheckpoint;
    private javax.swing.JRadioButton rbStart;
    private javax.swing.JRadioButton rbStartCheckpoint;
    private javax.swing.JRadioButton rbUpdate;
    private javax.swing.ButtonGroup rbgActionType;
    // End of variables declaration//GEN-END:variables
    //[end]
}
